-- update_clinic_websites.sql
-- Auto-generated by scripts/find_websites.ts
-- Contains 0 high-confidence matches only
-- REVIEW website_candidates.json before running this file!
-- Low-confidence matches require manual verification.

-- No high-confidence matches found this run.
